### ISSUE TITLE
Compile simdat error

### ISSUE THREAD

**Issue by chenlei199110** [tammyyang/simdat#2]
Hello!I am a postgraduate student from Chongqing university in China. Follow your steps，I compile Cyphon in core file. Executing until  "To rebuild", it does not pass, the error is as follows:

Compiling ./image.pyx because it changed.
Compiling ./math_tools.pyx because it changed.
[1/2] Cythonizing ./image.pyx
[2/2] Cythonizing ./math_tools.pyx

Error compiling Cython file:
------------------------------------------------------------
...
                start_pos = start

        return max_size, start_pos

    def area(self, size):
        return reduce(mul, size)
              ^
------------------------------------------------------------

math_tools.pyx:84:15: undeclared name not builtin: reduce
Traceback (most recent call last):
  File "setup.py 

", line 20, in <module>
ext_modules = cythonize("./*.pyx"),
  File "/home/guoq/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py 

", line 1039, in cythonize
    cythonize_one(*args)
  File "/home/guoq/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py 

", line 1161, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: ./math_tools.pyx_

I tried various methods but did not solve it. If you can answer my question I will not be grateful. Thank you!

**Comment by tammyyang** [comment]
Hi

I don't think you even need to rebuild now, sorry for the confusion.
You should be able to use any module directly without building it as so. Let me know if you have any question about it.
